name: Metrics
on:
  # Update setiap 24 jam
  schedule: [{cron: "0 0 * * *"}]
  # Bisa dijalankan manual
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token standar GitHub (Gak perlu setting apa-apa)
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Target file gambar
          filename: metrics.plugin.languages.svg
          
          # Tampilkan Plugin Bahasa
          plugin_languages: yes
          plugin_languages_ignored: html, css # Opsional: sembunyikan CSS kalau mau
          plugin_languages_limit: 8
          
          # --- INI BAGIAN AJAIBNYA (CUSTOM COLOR) ---
          # HTML kita paksa jadi BIRU (#0075f2)
          # Blade kita paksa jadi KUNING (#f7df1e)
          # Astro kita paksa jadi UNGU (#bc02bb)
          # PHP kita paksa jadi HIJAU (#4F5D95)
          plugin_languages_colors: "html:#0075f2, blade:#f7df1e, astro:#bc02bb, php:#777bb4"
